---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: home-assistant
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.homeAssistant.pvc.storageClass }}
  storageClassName: {{ .Values.homeAssistant.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.homeAssistant.pvc.size }}
{{- if .Values.zwavejs.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs2mqtt-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: zwavejs2mqtt
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.zwavejs.pvc.storageClass }}
  storageClassName: {{ .Values.zwavejs.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.zwavejs.pvc.size }}
{{- end }}
